version: '3.8'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/app             # Споделя цялата текуща директория с /app в контейнера
      - /app/node_modules  # Запазва node_modules в контейнера, предотвратявайки презапис от хоста
    environment:
      - CHOKIDAR_USEPOLLING=true  # Указва на Chokidar (използван от някои HMR процеси) да ползва polling
